INSERT INTO tb_conversation_links_course (link, id_course_id, id_language_id, created_at)
VALUES
       ('https://www.cursoemvideo.com/curso/html5-css3-modulo1/',(SELECT id FROM tb_conversation_courses_ctg c WHERE c.name = 'HTML5 CSS3 Modulo 1'),(SELECT id FROM tb_conversation_languages_ctg l WHERE l.name = 'HTML e CSS'),DATE ('now')),
       ('https://www.cursoemvideo.com/curso/curso-html5-e-css3-modulo-2-de-5-40-horas/',(SELECT id FROM tb_conversation_courses_ctg c WHERE c.name = 'HTML5 CSS3 Modulo 2'),(SELECT id FROM tb_conversation_languages_ctg l WHERE l.name = 'HTML e CSS'),DATE ('now')),
       ('https://www.cursoemvideo.com/curso/curso-html5-e-css3-modulo-3-de-5-40-horas/',(SELECT id FROM tb_conversation_courses_ctg c WHERE c.name = 'HTML5 CSS3 Modulo 3'),(SELECT id FROM tb_conversation_languages_ctg l WHERE l.name = 'HTML e CSS'),DATE ('now')),
       ('https://www.youtube.com/playlist?list=PLnDvRpP8BneyVA0SZ2okm-QBojomniQVO',(SELECT id FROM tb_conversation_courses_ctg c WHERE c.name = 'React JS'),(SELECT id FROM tb_conversation_languages_ctg l WHERE l.name = 'React JS'),DATE ('now')),
       ('https://www.youtube.com/playlist?list=PLGxZ4Rq3BOBoSRcKWEdQACbUCNWLczg2G',(SELECT id FROM tb_conversation_courses_ctg c WHERE c.name = 'Angular JS'),(SELECT id FROM tb_conversation_languages_ctg l WHERE l.name = 'Angular JS'),DATE ('now')),
       ('https://www.cursoemvideo.com/curso/curso-de-algoritmo/',(SELECT id FROM tb_conversation_courses_ctg c WHERE c.name = 'Logica de Programação'),(SELECT id FROM tb_conversation_languages_ctg l WHERE l.name = 'Lógica de Programação'),DATE ('now')),
       ('https://www.youtube.com/playlist?list=PLGxZ4Rq3BOBq0KXHsp5J3PxyFaBIXVs3r',(SELECT id FROM tb_conversation_courses_ctg c WHERE c.name = 'Java Iniciante'),(SELECT id FROM tb_conversation_languages_ctg l WHERE l.name = 'Java '),DATE ('now')),
       ('https://www.youtube.com/playlist?list=PLGxZ4Rq3BOBoqYyFWOV_YbfBW80YGAGEI',(SELECT id FROM tb_conversation_courses_ctg c WHERE c.name = 'Java Intermediário'),(SELECT id FROM tb_conversation_languages_ctg l WHERE l.name = 'Java '),DATE ('now')),
       ('https://www.youtube.com/playlist?list=PLvE-ZAFRgX8hnECDn1v9HNTI71veL3oW0',(SELECT id FROM tb_conversation_courses_ctg c WHERE c.name = 'Python Intermediário'),(SELECT id FROM tb_conversation_languages_ctg l WHERE l.name = 'Python'),DATE ('now')),
       ('https://www.udemy.com/course/python-3-na-web-com-django-basico-intermediario/',(SELECT id FROM tb_conversation_courses_ctg c WHERE c.name = 'Python Django'),(SELECT id FROM tb_conversation_languages_ctg l WHERE l.name = 'Python'),DATE ('now')),
       ('https://www.cursoemvideo.com/curso/javascript/',(SELECT id FROM tb_conversation_courses_ctg c WHERE c.name = 'JavaScript Iniciante'),(SELECT id FROM tb_conversation_languages_ctg l WHERE l.name = 'JavaScript'),DATE ('now')),
       ('https://www.youtube.com/playlist?list=PLJ_KhUnlXUPtbtLwaxxUxHqvcNQndmI4B',(SELECT id FROM tb_conversation_courses_ctg c WHERE c.name = 'Node JS'),(SELECT id FROM tb_conversation_languages_ctg l WHERE l.name = 'JavaScript'),DATE ('now')),
       ('https://www.youtube.com/playlist?list=PLPs3nlHFeKTr-aDDvUxU971rPSVTyQ6Bn',(SELECT id FROM tb_conversation_courses_ctg c WHERE c.name = 'Kotlin'),(SELECT id FROM tb_conversation_languages_ctg l WHERE l.name = 'Kotlin'),DATE ('now')),
       ('https://www.cursoemvideo.com/curso/curso-de-git-e-github/',(SELECT id FROM tb_conversation_courses_ctg c WHERE c.name = 'Git e Github'),(SELECT id FROM tb_conversation_languages_ctg l WHERE l.name = 'Git e Github'),DATE ('now')),
       ('https://www.cursoemvideo.com/curso/redes-de-computadores/',(SELECT id FROM tb_conversation_courses_ctg c WHERE c.name = 'Redes de computadores'),(SELECT id FROM tb_conversation_languages_ctg l WHERE l.name = 'Redes de computadores'),DATE ('now')),
       ('https://www.youtube.com/playlist?list=PLedtsFT8ymsgVCqgLvPiSrfYeGdujcqvv',(SELECT id FROM tb_conversation_courses_ctg c WHERE c.name = 'Criação de automação de testes'),(SELECT id FROM tb_conversation_languages_ctg l WHERE l.name = 'Criação de automação de testes'),DATE ('now')),
       ('https://www.cursoemvideo.com/curso/mysql/',(SELECT id FROM tb_conversation_courses_ctg c WHERE c.name = 'Banco de dados MySql'),(SELECT id FROM tb_conversation_languages_ctg l WHERE l.name = 'Banco de dados'),DATE ('now'));


